---
resources:
- name: source-repo
  type: git
  source:
    uri: {{git-source-repo-uri}}
- name: build-out-repo
  type: git
  source:
    branch: master
    uri: {{git-concourse-repo-uri}}
    disable_ci_skip: true
- name: PCF
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}
- name: cf-env
  type: cf-cli-resource
  source:
    api: {{pws-api}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true     

jobs:
- name: build-deploy
  public: true
  serial: true
  plan:
  - get: source-repo
    trigger: true
  - get: build-out-repo
    trigger: true
  - task: build
    file: build-out-repo/ci/tasks/build-ant.yml
  - put: PCF
    params:
      manifest: build-output/manifest.yml
