---
resource_types:
- name: cf-cli-resource
  type: docker-image
#  source:
#    repository: nulldriver/cf-cli-resource
#    tag: latest
  source:    
    repository: 10.197.37.26:5000/cf-cli-resource-rev
    tag: 'latest'
    insecure_registries: [ "10.197.37.26:5000" ]     
    
resources:
- name: source-repo
  type: git
  source:
    uri: {{git-source-repo-uri}}
- name: build-out-repo
  type: git
  source:
    branch: master
    uri: {{git-concourse-repo-uri}}
    disable_ci_skip: true
- name: cf-env
  type: cf-cli-resource
  source:
    api: {{pws-api}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    org: {{pws-organization}}    
    space: {{pws-space}}    
    skip_cert_check: true     

jobs:
- name: build-deploy
  public: true
  serial: true
  plan:
  - get: source-repo
    trigger: true
  - get: build-out-repo
    trigger: true
  - task: build
    file: build-out-repo/ci/tasks/build-ant.yml
  - put: cf-zero-downtime-push
    resource: cf-env
    params:
      command: zero-downtime-push
      manifest: build-output/manifest.yml
