groups:
- name: main
  jobs:
  - build-deploy-new-app
  - switch-route-between-old-and-new

resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest
    
resources:
- name: source-repo
  type: git
  source:
    uri: {{git-source-repo-uri}}
- name: build-out-repo
  type: git
  source:
    branch: master
    uri: {{git-concourse-repo-uri}}
    disable_ci_skip: true
- name: PCF
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}
- name: cf-env
  type: cf-cli-resource
  source:
    api: {{pws-api}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true    

jobs:
- name: build-deploy-new-app
  public: true
  serial: true
  plan:
  - get: source-repo
    trigger: true
  - get: build-out-repo
    trigger: false
  - task: prepare-app-manifest
    file: build-out-repo/ci/tasks/bluegreen/app-manifest-prep.yml
    params:
      app_name: {{appname}}    
      app_name_new: {{appname-new}} 
      app_domain: {{pws-app-domain}}
  - task: build
    file: build-out-repo/ci/tasks/build-maven.yml      
  - put: PCF
    params:
      manifest: source-repo/manifest-new.yml
      path: build-output/*.jar
- name: switch-route-between-old-and-new
  public: true
  serial: true
  plan:
  - get: source-repo
    trigger: true
    passed:
      - build-deploy-new-app
  - put: cf-map-orginal-route-to-new-app
    resource: cf-env
    params:
      command: map-route
      org: {{pws-organization}}
      space: {{pws-space}}
      app_name: {{appname-new}}
      domain: {{pws-app-domain}}
      hostname: {{appname}}
  - try:
      put: cf-rename-orginal-app-name-to-old
      resource: cf-env
      params:
        command: rename
        org: {{pws-organization}}
        space: {{pws-space}}      
        app_name: {{appname}}
        new_app_name: {{appname-old}}
  - put: cf-rename-new-app-to-orginal-app-name
    resource: cf-env
    params:
      command: rename
      org: {{pws-organization}}
      space: {{pws-space}}      
      app_name: {{appname-new}}
      new_app_name: {{appname}}      
  - try:
      put: cf-unmap-orginal-route-from-old-app
      resource: cf-env
      params:
        command: unmap-route
        org: {{pws-organization}}
        space: {{pws-space}}
        app_name: {{appname-old}}
        domain: {{pws-app-domain}}
        hostname: {{appname}}
  - put: cf-unmap-temporary-route-from-new-app
    resource: cf-env
    params:
      command: unmap-route
      org: {{pws-organization}}
      space: {{pws-space}}
      app_name: {{appname}}
      domain: {{pws-app-domain}}
      hostname: {{appname-new}}      
