---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 'latest'

inputs:
  - name: source-repo
  - name: build-out-repo
  
outputs:
  - name: build-output

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    ls -la
    sh build-out-repo/ci/tasks/build-ant.sh
