---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: build-out-repo

outputs:
- name: output

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    ls -la
    sh build-out-repo/ci/tasks/bluegreen/app-manifest-prep.sh
