---
platform: linux

image_resource:
  type: docker-image
#  source:
#    repository: busybox
#    tag: "latest"
  source:    
    repository: 10.197.37.26:5000/busybox
    tag: 'latest'
    insecure_registries: [ "10.193.193.26:5000" ]     

inputs:
  - name: source-repo
  - name: build-out-repo
outputs:
  - name: source-repo

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    ls -la
    sh build-out-repo/ci/tasks/bluegreen/app-manifest-prep.sh
