---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: "latest"

inputs:
  - name: source-repo
  - name: build-out-repo
outputs:
  - name: source-repo

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    ls -la
    sh build-out-repo/ci/tasks/bluegreen/app-manifest-prep.sh
